# This file is autogenerated by the ./cabal2nix script.
# Re-run ./cabal2nix when the dependencies in the cabal
# file have changed.

{ mkDerivation, array, base, containers, directory, filepath
, parsec, stdenv, wl-pprint
}:
mkDerivation {
  pname = "lvmlib";
  version = "1.2";
  src = ./.;
  isLibrary = true;
  isExecutable = true;
  libraryHaskellDepends = [
    array base containers directory filepath parsec wl-pprint
  ];
  executableHaskellDepends = [
    array base containers directory filepath parsec wl-pprint
  ];
  homepage = "http://www.cs.uu.nl/wiki/bin/view/Helium/WebHome";
  description = "The Lazy Virtual Machine (LVM)";
  license = stdenv.lib.licenses.bsd3;
}
